config/routes.rb
Inspire::Application.routes.draw do

  devise_for :users
  resources :users
  get "pages/home"
  get "about" => "pages#about"
  get "contact" => "pages#contact"
  resources :books do
    collection do
      get 'search'
      post 'load_from_amazon'
    end
    resources :inspirations do
      resources :comments, only: [:create, :edit, :destroy]
      get 'up-vote', to: 'votes#up_vote', as: :up_vote
      get 'down-vote', to: 'votes#down_vote', as: :down_vote
    end
  end

  resources :inspirations do
      resources :comments, only: [:create, :edit, :destroy]
    end

  resources :favorites, only: [:create, :destroy]
    
  root "books#index"

end

app/models/inspiration.rb
class Inspiration < ActiveRecord::Base
	belongs_to :user
	belongs_to :book
	has_many :comments
	has_many :votes, dependent: :destroy
	has_many :favorites, dependent: :destroy

	delegate :title, :link, :to => :book, :prefix => true

	def new_comment_path
	  Rails.application.routes.url_helpers.new_book_inspiration_comment_path(book, self)
	end
 
	def serializable_hash(*args)
	  super.merge 'new_comment_path' => new_comment_path
	end
end

app/controllers/inspirations_controller.rb
class InspirationsController < ApplicationController
  before_action :set_inspiration, only: [:show, :edit, :update, :destroy]
  before_action :set_book
  before_action :authenticate_user!, except: [:show]
  before_action :correct_user, only: [:edit, :update, :destroy]

  # GET /inspirations
  # GET /inspirations.json
  def index
    @inspirations = Inspiration.all
  end

  # GET /inspirations/1
  # GET /inspirations/1.json
  def show
    @comment = Comment.new( :inspiration => @inspiration )
    @comments = Comment.where(inspiration_id: @inspiration.id)
  end

  def up_votes
    self.votes.where(value: 1).count
  end

  def down_votes
    self.votes.where(value: -1).count
  end

  # GET /inspirations/new
  def new
    @inspiration = Inspiration.new
  end

  # GET /inspirations/1/edit
  def edit
  end

  # POST /inspirations
  # POST /inspirations.json
  def create
    @inspiration = Inspiration.new(inspiration_params)
    @inspiration.user_id = current_user.id
    @inspiration.book_id = @book.id

    respond_to do |format|
      if @inspiration.save
        format.html { redirect_to @book, notice: 'Inspiration was successfully created.' }
        format.json { render action: 'show', status: :created, location: @inspiration }
      else
        format.html { render action: 'new' }
        format.json { render json: @inspiration.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /inspirations/1
  # PATCH/PUT /inspirations/1.json
  def update
    respond_to do |format|
      if @inspiration.update(inspiration_params)
        format.html { redirect_to @book, notice: 'Inspiration was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @inspiration.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /inspirations/1
  # DELETE /inspirations/1.json
  def destroy
    @inspiration.destroy
    respond_to do |format|
      format.html { redirect_to inspirations_url }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_inspiration
      @inspiration = Inspiration.find(params[:id])
    end

    def set_book
      @book = Book.find(params[:book_id])
    end

    def correct_user
      @inspiration = current_user.inspirations.find_by(id: params[:id])
      redirect_to books_path, alert: "Sorry. This isn't yours." if @inspiration.nil?
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def inspiration_params
      params.require(:inspiration).permit(:quote, :page_number, :likes, :value)
    end

    def points_dammit
      @inspiration.votes.sum(:value).count
    end
end

app/helpers/inspirations_helper.rb
module InspirationsHelper
end

app/views/inspirations/_form.html.erb
<%= form_for([@book, @inspiration], :html => { :class => "user-form" }) do |f| %>
  <% if @inspiration.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@inspiration.errors.count, "error") %> prohibited this inspiration from being saved:</h2>

      <ul>
      <% @inspiration.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :quote %><br>
    <%= f.text_area :quote %>
  </div>
  <div class="field">
    <%= f.label :page_number %><br>
    <%= f.number_field :page_number %>
  </div>
  <div class="field">
    <%= f.label :likes %><br>
    <%= f.number_field :likes %>
  </div>

   <div class="user-submit-wrap">
    <p class="clearfix">
    <%= f.submit class: "user-submit" %>
  </p>
  </div>
<% end %>

app/views/inspirations/_inspiration.html.erb
<div class="box box-default" style="cursor: pointer;" data-toggle="modal" data-target="#inspirationModal<%= inspiration.id %>">
  <div class="panel-body">
  
    <%= inspiration.quote %>
    <br>
 
    <%= link_to book_inspiration_path(inspiration.book_id, inspiration) do %>
	    <span class="glyphicon glyphicon-comment"></span> <%= inspiration.comments.size %>
    <% end %>
  </div>
</div>
 
<%= render partial: 'inspirations/modal', locals: { inspiration: inspiration } %>

app/views/inspirations/_modal.html.erb
<!-- Modal -->
<div id="inspirationModal<%= inspiration.id %>" class="modal fade" tabindex="-1" role="dialog" aria-labelledby="quoteTitle" aria-hidden="true">
  <div class="modal-dialog modal-lg">
 
    <div class="modal-content">
 
      <div class="modal-body" id="quoteBody">
        <div class="container-fluid">
          <button type="button" class="close" data-dismiss="modal" aria-hidden="true">
          <span>&times;</span><span class="sr-only">Close</span>
        </button>
          <div class="row">
            <div class="vote-arrows pull-left">
              <div id="<%= 'vote-submit' + inspiration.id.to_s %>">
                <%= render partial: 'votes/voter', locals: { book: @book, inspiration: inspiration } %>
              </div>
              <div id="<%= 'favorite-submit' + inspiration.id.to_s %>">
                <%= render partial: 'favorites/favorite_inspiration', locals: { book: @book, inspiration: inspiration } %>
              </div>
            </div>

            <div class="col-md-7">
              <div class="inspiration">
                <p id="inspiration-quote"  class="inspiration-text">
                  <%= inspiration.quote %>
                </p>
   
                <div class="pull-right">
                  <p class="inspiration-credit">- <%= link_to @book.title, @book.link, id: 'book-link' %></p>
                  <p class="inspiration-credit">pg. <span id="page_number">0<span></p>
                </div>
              </div>
              
              <% if current_user.try(:admin?) %>
                <%= link_to edit_book_inspiration_path(inspiration.book_id, inspiration) do %>
                  <span class="glyphicon glyphicon-pencil"></span>
                  <span style="padding-right:8px">Edit</span>
                <% end %>
           
                <%= link_to book_inspirations_path(inspiration.book_id), method: :delete, data: { confirm: 'Are you sure?' } do %>
                  <span class="glyphicon glyphicon-trash"></span>
                    Delete
                <% end %>
              <% end %>
              </div>

            <div class="col-md-5">
              <%= render partial: "layouts/social_for_inspiration", locals: { book: @book, inspiration: inspiration } %>
              
              <% if inspiration.comments.size > 0 %>
              <div id="inspiration-comments" class="comment-container scroll-pane" >
              <%= render inspiration.comments.reverse %>
              </div>
              <div class="comment-container">
                <%= render partial: '/comments/simpleComment', locals: { inspiration: inspiration } %>
              </div>
              
              <% else %>
              
              <div id="inspiration-comments" class="comment-container scroll-pane" >
                <p><em>Have something to say about this?</em></p>
              </div>
              <div class="center">
                <%= render partial: '/comments/simpleComment', locals: { inspiration: inspiration } %>
              </div>
              <% end %>
            </div>
          </div><!-- end the row -->
        </div><!-- end the container -->
      </div><!-- end the modal boday -->
    </div>
  </div>
</div>
<!-- Modal -->

<style media="screen">
  .inspiration { background: url('http://www.tocofi.com/wp-content/uploads/2012/09/instagram-art-gallery_digital-photography-4.jpg') no-repeat;
  }
</style>

app/views/inspirations/_showPartial.html.erb
<div class="container-fluid">
	<div class="row">
		<div class="col-md-7 inspiration">
			<p class="inspiration-text">
			  <%= inspiration.quote %><br>
			  <div class="pull-right">
			<p class="inspiration-credit">- <%= link_to @book.title, @book.link %></p>
			<p class="inspiration-credit">pg. <%= inspiration.page_number %></p>				
			</div>
			</p>

			<%= link_to 'Edit', edit_book_inspiration_path(@book, inspiration) %> |
			<%= link_to 'Back', book_path(@book) %>
		</div>

		<div class="col-md-4">
			<div class="comment-container">
				<% @comments.each do |comment| %>
				<div class="comment">
				 <%= comment.content %><br>
				 <%= link_to 'Edit', edit_book_inspiration_comment_path(@book, inspiration, comment) %> |
	        	 <%= link_to 'Delete', book_inspiration_comment_path(@book, inspiration, comment), method: :delete, data: { confirm: 'Are you sure?' } %>
	        	</div>
	        </div>
        	 <% end %>
        	
        	 <%= link_to 'New Comment', new_book_inspiration_comment_path(@book, inspiration), class:"btn btn-primary" %>
		</div>
	</div>
</div>

app/views/inspirations/edit.html.erb
<h1>Editing inspiration</h1>

<%= render 'form' %>

<%= link_to 'Show', book_inspiration_path(@book, @inspiration) %> |
<%= link_to 'Back', book_path(@book) %>

app/views/inspirations/index.html.erb
<h1>Listing inspirations</h1>

<table>
  <thead>
    <tr>
      <th>Quote</th>
      <th>Page number</th>
      <th>Likes</th>
      <th></th>
      <th></th>
      <th></th>
    </tr>
  </thead>

  <tbody>
    <% @inspirations.each do |inspiration| %>
      <tr>
        <td><%= inspiration.quote %></td>
        <td><%= inspiration.page_number %></td>
        <td><%= inspiration.likes %></td>
        <td><%= link_to 'Show', book_inspiration_path %></td>
        <td><%= link_to 'Edit', edit_inspiration_path(inspiration) %></td>
        <td><%= link_to 'Destroy', inspiration, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Inspiration', new_inspiration_path %>

app/views/inspirations/new.html.erb
<div class="signup">
<h1>New inspiration</h1>

<%= render 'form' %>

<%= link_to 'Back', book_path(@book) %>
</div>

app/views/inspirations/show.html.erb
<% if current_user.try(:admin?) %>
<%= link_to 'Edit', edit_book_inspiration_path(@book, @inspiration) %> |
<% end %>
<%= link_to 'Back', book_path(@book) %>
<div class="inspiration-collection container-fluid">
	<div class="row">
		<div class="col-md-7 inspiration">
			<p class="inspiration-text">
			  <%= @inspiration.quote %><br>
			  <div class="pull-right">
			<p class="inspiration-credit">- <%= link_to @book.title, @book.link %></p>
			<p class="inspiration-credit">pg. <%= @inspiration.page_number %></p>				
			</div>
			</p>
			
		</div>

		<div class="col-md-5">
			<% if @inspiration.comments.size > 0 %>
              <div id="inspiration-comments" class="comment-container scroll-pane" >
              <%= render @inspiration.comments.reverse %>
              </div>
              <div class="comment-container">
                <%= render partial: '/comments/simpleComment', locals: { inspiration: @inspiration } %>
              </div>
              
              <% else %>
              
              <div id="inspiration-comments" class="comment-container scroll-pane" >
                <p><em>Have something to say about this?</em></p>
              </div>
              <div class="center">
                <%= render partial: '/comments/simpleComment', locals: { inspiration: @inspiration } %>
              </div>
              <% end %>
		</div>
	</div>
</div>