config/routes.rb
Inspire::Application.routes.draw do

  devise_for :users
  resources :users
  get "pages/home"
  get "about" => "pages#about"
  get "contact" => "pages#contact"
  resources :books do
    collection do
      get 'search'
      post 'load_from_amazon'
    end
    resources :inspirations do
      resources :comments, only: [:create, :edit, :destroy]
      get 'up-vote', to: 'votes#up_vote', as: :up_vote
      get 'down-vote', to: 'votes#down_vote', as: :down_vote
    end
  end

  resources :inspirations do
      resources :comments, only: [:create, :edit, :destroy]
    end

  resources :favorites, only: [:create, :destroy]
    
  root "books#index"

end

app/models/comment.rb
class Comment < ActiveRecord::Base
	belongs_to :user
	belongs_to :inspiration

	delegate :book, :to => :inspiration, :prefix => true

	validates :content, presence: true
 
	def to_edit_path
	  Rails.application.routes.url_helpers.edit_book_inspiration_comment_path inspiration_book, inspiration, self
	end
 
	def to_path
	  Rails.application.routes.url_helpers.book_inspiration_comment_path inspiration_book, inspiration, self
	end
 
	def serializable_hash(*args)
	  super.merge 'path' => to_path, 'edit_path' => to_edit_path
	end
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  before_action :set_comment, only: [:show, :edit, :update, :destroy]
  before_action :set_book
  before_action :set_inspiration
  before_action :authenticate_user!

  # GET /comments
  # GET /comments.json
  def index
    @comments = Comment.all.order("created_at DESC")
  end

  # GET /comments/1
  # GET /comments/1.json
  def show
  end

  # GET /comments/new
  def new
    @inspiration = Inspiration.find(params[:inspiration_id])
    @comment = Comment.new(params[:comment])
    #@comment = Comment.new
  end

  # GET /comments/1/edit
  def edit
  end

  # POST /comments
  # POST /comments.json
  def create
    @inspiration = Inspiration.find(params[:inspiration_id])
    @comment = Comment.new(comment_params)
    @comment.user_id = current_user.id
    @comment.inspiration_id = @inspiration.id
    

    respond_to do |format|
      if @comment.save
        format.html { redirect_to @book, notice: 'Comment was successfully created.' }
        format.json { render action: 'show', status: :created, location: @comment }
        format.js
      else
        format.html { render action: 'new' }
        format.json { render json: @comment.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /comments/1
  # PATCH/PUT /comments/1.json
  def update
    respond_to do |format|
      if @comment.update(comment_params)
        format.html { redirect_to @comment, notice: 'Comment was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @comment.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /comments/1
  # DELETE /comments/1.json
  def destroy
    @comment = Comment.find(params[:id])
    @comment.destroy
    respond_to do |format|
      format.html { redirect_to @book }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_comment
      @comment = Comment.find(params[:id])
    end

    def set_book
      @book = Book.find(params[:book_id])
    end

    def set_inspiration
      @inspiration = Inspiration.find(params[:inspiration_id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def comment_params
      params.require(:comment).permit(:content, :user_id, :inspiration_id)
    end
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/views/comments/_comment.html.erb
<div class="comment row">
	<div class="comment-img col-sm-2 col-md-2 col-lg-2">
		<%= image_tag(comment.user.profile_image.url(:thumb), class: 'img-circle') %>
	</div>
	<div class="col-sm-10 col-md-10 col-lg-10">
		<div class="comment-title"><p><%= comment.user.username %></p></div>
	 	<%= comment.content %><br />
	 	<div class="comment-footer">
	 		<div class="col-sm-4 col-md-4 col-lg-4"><%= comment.created_at.strftime("%b %d, %Y") %></div>
	 		<div class="col-sm-4 col-md-4 col-lg-4"></div>
	 		<div class="col-sm-4 col-md-4 col-lg-4">
	 		<% if current_user && comment.user == current_user %>
		 	<%= link_to 'Edit', comment.to_edit_path, class: 'comment-footer' %> |
		 	<%= link_to 'Delete', comment.to_path, method: :delete, data: { confirm: 'Are you sure?' }, class: 'comment-footer' %>
		 	<% end %>
		 	</div>
	 	</div>
 	</div>
</div>

app/views/comments/_form.html.erb
<%= form_for([@book, @inspiration, @comment]) do |f| %>
  <% if @comment.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@comment.errors.count, "error") %> prohibited this comment from being saved:</h2>

      <ul>
      <% @comment.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :content %><br>
    <%= f.text_area :content %>
  </div>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/comments/_simpleComment.html.erb
<%= form_for [@book, inspiration, @comment], :html => { :class => "comment-form", remote: true } do |f| %>
<%= f.hidden_field :inspiration_id %> 
  <% if @comment.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@comment.errors.count, "error") %> prohibited this comment from being saved:</h2>

      <ul>
      <% @comment.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.text_field :content, placeholder: "Add a comment & hit enter.", :id => 'comment_submit' + inspiration.id.to_s %>
  </div>

<% end %>

app/views/comments/create.js.erb
$('#comment_submit<%= @inspiration.id.to_s %>').val('');
$('#comment_submit<%= @inspiration.id.to_s %>').attr('placeholder', 'Add a comment & hit enter.');
$('#inspiration-comments').html('<%= escape_javascript(render @inspiration.comments.reverse) %>');

app/views/comments/edit.html.erb
<h1>Editing comment</h1>

<%= render 'form' %>

<%= link_to 'Show', book_inspiration_comment_path(@book, @inspiration,@comment) %> |
<%= link_to 'Back', book_inspiration_comments_path(@book, @inspiration) %>

app/views/comments/index.html.erb
<h1>Listing comments</h1>

<table>
  <thead>
    <tr>
      <th>Content</th>
      <th>User</th>
      <th>Inspiration</th>
      <th></th>
      <th></th>
      <th></th>
    </tr>
  </thead>

  <tbody>
    <% @comments.each do |comment| %>
      <tr>
        <td><%= comment.content %></td>
        <td><%= comment.user_id %></td>
        <td><%= comment.inspiration_id %></td>
        <td><%= link_to 'Show', book_inspiration_comment_path(@book, @inspiration, comment) %></td>
        <td><%= link_to 'Edit', edit_book_inspiration_comment_path(@book, @inspiration, comment) %></td>
        <td><%= link_to 'Destroy', book_inspiration_comment_path(@book, @inspiration, comment), method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Comment', new_book_inspiration_comment_path(@book, @inspiration) %>

app/views/comments/new.html.erb
<h1>New comment</h1>

<%= render 'form' %>

<%= link_to 'Back', book_inspiration_comments_path(@book, @inspiration) %>

app/views/comments/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Content:</strong>
  <%= @comment.content %>
</p>

<p>
  <strong>User:</strong>
  <%= @comment.user_id %>
</p>

<p>
  <strong>Inspiration:</strong>
  <%= @comment.inspiration_id %>
</p>

<%= link_to 'Edit', edit_book_inspiration_comment_path(@book, @inspiration,@comment) %> |
<%= link_to 'Back', book_path(@book) %>