config/routes.rb
Inspire::Application.routes.draw do

  devise_for :users
  resources :users
  get "pages/home"
  get "about" => "pages#about"
  get "contact" => "pages#contact"
  resources :books do
    collection do
      get 'search'
      post 'load_from_amazon'
    end
    resources :inspirations do
      resources :comments, only: [:create, :edit, :destroy]
      get 'up-vote', to: 'votes#up_vote', as: :up_vote
      get 'down-vote', to: 'votes#down_vote', as: :down_vote
    end
  end

  resources :inspirations do
      resources :comments, only: [:create, :edit, :destroy]
    end

  resources :favorites, only: [:create, :destroy]
    
  root "books#index"

end

app/models/book.rb
class Book < ActiveRecord::Base
	belongs_to :user
	has_attached_file :image, :styles => { :medium => "300x300>", :thumb => "100x100>" }
	has_many :inspirations
	has_many :comments, through: :inspirations
	has_many :favorites, through: :inspirations

	searchkick

end

app/controllers/books_controller.rb
require "html_truncator"
require 'amazon/aws/search'

class BooksController < ApplicationController
  before_action :set_book, only: [:show, :edit, :update, :destroy]
  before_action :authenticate_user!, except: [:index, :show, :search]
  before_action :correct_user, only: [:edit, :update, :destroy]

  #include amazon helpers
  include Amazon::AWS
  include Amazon::AWS::Search

  def search
    if params[:search].present?
      @books = Book.search(params[:search], fields: [:title])

        is = ItemSearch.new( 'Books', { 'Title' => params[:search],
                                        'MerchantId' => 'Amazon' })

        # 'Large' required for images 
        # Could also be 'Small'' for just title & product group
        rg = ResponseGroup.new(:Large)


        # Perform the Search
        req = Request.new( ENV['AWS_ACCESS_KEY_ID'], 'inspirati0caf-20', 'us', false)
        req.config['secret_key_id'] = ENV['AWS_SECRET_ACCESS_KEY']

        resp = req.search( is, rg )

        @results = []
        resp["item_search_response"][0].items[0].item.each do |i|
        # Grab the attributes we want
          title = i.item_attributes.title[0].to_s[0,60]
          group = i.item_attributes.product_group.to_s
          image = amazon_image_set(i.image_sets[0].image_set)
          pub_date = i.item_attributes.publication_date.to_s
          genre = i.item_attributes.genre
          isbn = i.item_attributes.isbn.to_s
          url = i.detail_page_url

          # Add to results array
          @results << { :title => title, :group => group, :image => image, :publication_date => pub_date, :genre => genre, :isbn => isbn, :detail_page_url => url }
        end

        # Return results 0-100 as JSON
        #render :json => results[0..100]

        # If no results, Amazon::AWS throws an error, so we can rescue
        # TODO There's definitely a better way to handle this
        # rescue 
        # render :json => ["None"]
        # end

    else
      flash[:alert] = "Be sure to enter a keyword in your search."
      redirect_to root_path
    end
  end

  # GET /books
  # GET /books.json
  def index
    @books = Book.all.order("created_at DESC")
  end

  # GET /books/1
  # GET /books/1.json
  def show
    @inspirations = Inspiration.where(book_id: @book.id)
    @comment = Comment.new( :inspiration => @inspiration ) 

    def up_votes
      @inspiration.votes.where(value: 1).count
    end

    def down_votes
      @inspiration.votes.where(value: -1).count
    end

    def points
      @inspiration.votes.sum(:value).to_i
    end
 
  end

  # GET /books/new
  def new
    @book = current_user.books.build
  end

  # GET /books/1/edit
  def edit
  end

  # POST /books
  # POST /books.json
  def create
    @book = current_user.books.build(book_params)
    @book.preview = HTML_Truncator.truncate(@book.description, 20)

    respond_to do |format|
      if @book.save
        format.html { redirect_to @book, notice: 'Book was successfully created.' }
        format.json { render action: 'show', status: :created, location: @book }
      else
        format.html { render action: 'new' }
        format.json { render json: @book.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /books/1
  # PATCH/PUT /books/1.json
  def update
    @book.preview = HTML_Truncator.truncate(@book.description, 20)

    respond_to do |format|
      if @book.update(book_params)
        format.html { redirect_to @book, notice: 'Book was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @book.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /books/1
  # DELETE /books/1.json
  def destroy
    @book.destroy
    respond_to do |format|
      format.html { redirect_to books_url }
      format.json { head :no_content }
    end
  end

  def load_from_amazon
    isbn = params[:isbn]

    is = ItemLookup.new( 'ISBN', { 'ItemId' => isbn, 'SearchIndex' => 'Books'})

        # 'Large' required for images 
        # Could also be 'Small'' for just title & product group
        rg = ResponseGroup.new(:Large,:ItemAttributes)


        # Perform the Search
        req = Request.new( ENV['AWS_ACCESS_KEY_ID'], 'inspirati0caf-20', 'us', false)
        req.config['secret_key_id'] = ENV['AWS_SECRET_ACCESS_KEY']

        resp = req.search( is, rg )

        @results = []
        amazon_book = resp["item_lookup_response"][0].items[0].item.first
        # Grab the attributes we want
        title = amazon_book.item_attributes.title[0].to_s[0,60]
        group = amazon_book.item_attributes.product_group.to_s
        image = amazon_image_set(amazon_book.image_sets[0].image_set)
        pub_date = amazon_book.item_attributes.publication_date.to_s
        genre = amazon_book.item_attributes.genre
        isbn = amazon_book.item_attributes.isbn.to_s
        url = amazon_book.detail_page_url.to_s

          book = Book.find_or_create_by(isbn: isbn) do |book|
            book.title = title
            book.genre = genre
            book.date_publish = pub_date
            book.aws_image_url = image
            book.url = url

          book.save!
          end
          redirect_to book, notice: 'Book was successfully added.'
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_book
      @book = Book.find(params[:id])
    end

    def correct_user
      @book = current_user.books.find_by(id: params[:id])
      redirect_to books_path, alert: "Not authorized to edit this book" if @book.nil?
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def book_params
      params.require(:book).permit(:title, :link, :genre, :image, :description, :date_publish, :preview, :user_id)
    end

    # Helper function, only argument is an image_set
    # Returns the thumbnail_image url or ""
    # Instead of thumbnail_image, could be small_image, large_image
    def amazon_image_set(set)
      set[0].large_image.url.to_s
      rescue
       ""
    end
end

app/helpers/books_helper.rb
module BooksHelper
	def comment_number
		comment_count = []
		comment_count << (Comment.find_by inspiration_id: 1)
		return comment_count.length
	end
end

app/views/books/_amazonSearch.html.erb
<div class="featurette">
  <div class="container">
    <h2 class="featurette-title center">More Results</h2>
    <p class="lead center">Would you like to add a new book?</p>
    <div id="books2" class="transitions-enabled">
          <% @results.each do |book| %>
            <div class="books-box panel panel-default">
              <img src="<%= book[:image] %>">
              <div class="panel-body">
                <%= book[:title] %><br>
                <%= link_to "Add this book", load_from_amazon_books_path(isbn: book[:isbn]), method: "POST", :class => "btn btn-primary" %>
              </div>
            </div>
          <% end %>
        </div>
    </div>
</div>

app/views/books/_amazonSearchOnly.html.erb
  <div class="container">
    <h2 class="featurette-title center">Search Results</h2>
    <p class="lead center">Please add a new book.</p>
    <div id="books2" class="transitions-enabled">
          <% @results.each do |book| %>
            <div class="books-box panel panel-default">
              <img src="<%= book[:image] %>">
              <div class="panel-body">
                <%= book[:title] %><br>
                <%= link_to "Add this book", load_from_amazon_books_path(isbn: book[:isbn]), method: "POST", :class => "btn btn-primary" %>
              </div>
            </div>
          <% end %>
        </div>
    </div>

app/views/books/_book.html.erb
<%= link_to( image_tag(book.aws_image_url, width: "200px"), book.url, class: "book-image")%>
      <br>
      <%= render 'layouts/social' %>
      <div class="new-inspiration">
      <%= link_to book.url, class:"btn btn-success btn-lg" do %>
              <span class="glyphicon glyphicon-book"></span>  View on Amazon
            <% end %>
            <br>
            <br>
      <%= link_to new_book_inspiration_path(book), class:"btn btn-primary btn-lg" do %>
              <span class="glyphicon glyphicon-plus"></span> Add an inspiration
            <% end %>      
      </div>
      <%= link_to 'Edit', edit_book_path(book) %> |
      <%= link_to 'Back', books_path %>

app/views/books/_form.html.erb
<%= form_for(@book) do |f| %>
  <% if @book.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@book.errors.count, "error") %> prohibited this book from being saved:</h2>

      <ul>
      <% @book.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :title %><br>
    <%= f.text_field :title %>
  </div>
  <div class="field">
    <%= f.label :link %><br>
    <%= f.text_area :link %>
  </div>
  <div class="field">
    <%= f.label :genre %><br>
    <%= f.text_field :genre %>
  </div>
  
  <div class="field">
    <%= f.label :description %><br>
    <%= f.text_area :description %>
  </div>
  <div class="field">
    <%= f.label :date_publish %><br>
    <%= f.text_field :date_publish %>
  </div>

<div class="form-group">
    <%= f.label :image %>
    <%= f.file_field :image, class: "form-control" %>
  </div>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/books/_localSearch.html.erb
<div class="container">
<h2 class="featurette-title center">Search Results</h2>
<p class="lead center">Books that have already been added.</p>
<div id="books" class="transitions-enabled">
      <% @books.each do |book| %>
        <div class="books-box panel panel-default">
          <a href="<%= book_path(book) %>">
          <%= image_tag book.image.url(:medium) %></a>
          <div class="panel-body">
            <%= book.preview %>
            <br>
            <% if current_user && book.user == current_user %>
            <div style="margin: 10px" class="center">
              <%= link_to edit_book_path(book) do %>
              <span class="glyphicon glyphicon-pencil"></span>
              <span style="padding-right:8px">Edit</span>
              <% end %>
              <%= link_to book, method: :delete, data: { confirm: 'Are you sure?' } do %>
              <span class="glyphicon glyphicon-trash"></span>
              Delete
              <% end %>
            </div>
            <% end %>
          </div>
        </div>
      <% end %>
    </div>
  </div>

app/views/books/edit.html.erb
<h1>Editing book</h1>

<%= render 'form' %>

<%= link_to 'Show', @book %> |
<%= link_to 'Back', books_path %>

app/views/books/index.html.erb
<%= render 'pages/home' %>

<div class="featurette">
  <%= link_to 'New Book', new_book_path %>

    <div id="books" class="transitions-enabled">
      <% @books.each do |book| %>
        <div class="books-box panel panel-default">
          <a href="<%= book_path(book) %>">
          <%= image_tag book.aws_image_url %></a>
          <div class="panel-body">
            <%= book.preview %>
            <br>
            <% if current_user.try(:admin?) %>
            <div style="margin: 10px" class="center">
              <%= link_to edit_book_path(book) do %>
              <span class="glyphicon glyphicon-pencil"></span>
              <span style="padding-right:8px">Edit</span>
              <% end %>
              <%= link_to book, method: :delete, data: { confirm: 'Are you sure?' } do %>
              <span class="glyphicon glyphicon-trash"></span>
              Delete
              <% end %>
            </div>
            <% end %>
          </div>
        </div>
      <% end %>
    </div>
  </div>

app/views/books/new.html.erb
<h1>New book</h1>

<%= render 'form' %>

<%= link_to 'Back', books_path %>

app/views/books/search.html.erb
<% unless @books.empty? %>
<%= render "books/localSearch" %>
  <br>
  <br>
<%= render "books/amazonSearch" %>

<% else %>
<%= render "books/amazonSearchOnly" %>
<% end %>

app/views/books/show.html.erb
<div class="container-fluid">
  <div class="row">
    <div class="col-sm-2 col-md-2 col-lg-2">
      <%= render @book %>
    </div>
 
    <div class="col-sm-10 col-md-10 col-lg-10">
      <div id="inspiration-bg" class="transitions-enabled">
        <div id="inspirations">
          <%= render @inspirations %>
        </div>
      </div>
    </div>
 
    <!-- For seeing a grid that is flush <div class="col-sm-10 col-md-10 col-lg-10">
      <ul class="cbp-rfgrid">
        <% @inspirations.each do |inspiration| %>
        <li><a href="<%= book_inspiration_path(@book, inspiration) %>"><img src="http://www.lovethispic.com/uploaded_images/44844-Cute-Cat.png" /><div><h4><%= inspiration.quote %></h4></div></a></li>
        <% end %>
      </ul>
    </div> -->
    
  </div><!-- end the row-->
</div>