config/routes.rb
Inspire::Application.routes.draw do

  devise_for :users
  resources :users
  get "pages/home"
  get "about" => "pages#about"
  get "contact" => "pages#contact"
  resources :books do
    collection do
      get 'search'
      post 'load_from_amazon'
    end
    resources :inspirations do
      resources :comments, only: [:create, :edit, :destroy]
      get 'up-vote', to: 'votes#up_vote', as: :up_vote
      get 'down-vote', to: 'votes#down_vote', as: :down_vote
    end
  end

  resources :inspirations do
      resources :comments, only: [:create, :edit, :destroy]
    end

  resources :favorites, only: [:create, :destroy]
    
  root "books#index"

end

app/views/layouts/_header.html.erb
<nav class="navbar navbar-inverse" role="navigation">
  <div class="container">
    <!-- Brand and toggle get grouped for better mobile display -->
    <div class="navbar-header">
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <a class="navbar-brand" href="/">{ inspire }</a>
    </div>

    <!-- Collect the nav links, forms, and other content for toggling -->
    <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
      <ul class="nav navbar-nav navbar-right">
        <li><%= link_to "about", about_path %>
        <li><%= link_to "contact", contact_path %>
        <% if user_signed_in? %>
          <li class="dropdown">
          <a href="#" class="dropdown-toggle" data-toggle="dropdown"><%= image_tag(current_user.profile_image.url(:thumb), class: 'round-image-25 img-circle') %> <span class="caret"></span></a>
          <ul class="dropdown-menu" role="menu">
            <li><%= link_to "Edit profile", edit_user_registration_path %></li>
            <li><a href="#">Another action</a></li>
            <li><a href="#">Something else here</a></li>
            <li class="divider"></li>
            <li><%= link_to "Log out", destroy_user_session_path, method: :delete %></li>
        <% else %>
        <li><%= link_to "Sign up", new_user_registration_path %></li>
        <li><%= link_to "Sign in", new_user_session_path %></li>
        <% end %>
          </ul>
        </li>
      </ul>
    </div><!-- /.navbar-collapse -->
  </div><!-- /.container-fluid -->
</nav>

app/views/layouts/_header_inspiration.html.erb
<nav class="navbar navbar-inverse af-header" role="navigation">
  <div class="container af-inner">
    <!-- Brand and toggle get grouped for better mobile display -->
    <div class="navbar-header">
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#collapse-1">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <a class="navbar-brand" href="/">{ inspire }</a>
    </div>

    <ul class="nav navbar-nav">
    <div class="new-inspiration">
      <%= link_to new_book_inspiration_path(@book), class:"btn btn-primary" do %>
              <span class="glyphicon glyphicon-plus"></span> Add an inspiration
            <% end %>
    </div>
    </ul>

    <!-- Collect the nav links, forms, and other content for toggling -->
    <div class="collapse navbar-collapse" id="collapse-1">
      <ul class="nav navbar-nav navbar-right">
        <li><%= link_to "about", about_path %>
        <li><%= link_to "contact", contact_path %>
        <% if user_signed_in? %>
          <li class="dropdown">
          <%= image_tag @user.avatar.url(:thumb) %>
          <a href="#" class="dropdown-toggle" data-toggle="dropdown"><%= current_user.username %> <span class="caret"></span></a>
          <ul class="dropdown-menu" role="menu">
            <li><%= link_to "Edit profile", edit_user_registration_path %></li>
            <li><a href="#">Another action</a></li>
            <li><a href="#">Something else here</a></li>
            <li class="divider"></li>
            <li><%= link_to "Log out", destroy_user_session_path, method: :delete %></li>
        <% else %>
        <li><%= link_to "Sign up", new_user_registration_path %></li>
        <li><%= link_to "Sign in", new_user_session_path %></li>
        <% end %>
          </ul>
        </li>
      </ul>
    </div><!-- /.navbar-collapse -->
  </div><!-- /.container-fluid -->
</nav>

app/views/layouts/_inspiration_button.html.erb
<nav class="navbar navbar-default navbar-fixed-bottom" role="navigation">
  <div class="container">
    <!-- Brand and toggle get grouped for better mobile display -->
    <div class="new-inspiration">
      <%= link_to new_book_inspiration_path(@book), class:"btn btn-primary btn-lg" do %>
              <span class="glyphicon glyphicon-plus"></span> Add an inspiration
            <% end %>
    </div>
  </div><!-- /.container -->
</nav>

app/views/layouts/_jScrollpane.html.erb
<script>
  $(function()
  {
    $('.scroll-pane').jScrollPane({
    	contentWidth: '0px';
    });
  });
</script>

app/views/layouts/_social.html.erb
<div class="container-social">
    <div id="shareme" data-url="/books/<%= @book.id %>" data-text="Get inspired and share inspirations about <%= @book.title %>" data-title="share this page"></div>
</div>
<script>
$('#shareme').sharrre({
  share: {
    googlePlus: true,
    facebook: true,
    twitter: true,
    digg: true,
    delicious: true
  },
  enableTracking: true,
  buttons: {
    googlePlus: {size: 'tall', annotation:'bubble'},
    facebook: {layout: 'box_count'},
    twitter: {count: 'vertical'},
    digg: {type: 'DiggMedium'},
    delicious: {size: 'tall'}
  },
  hover: function(api, options){
    $(api.element).find('.buttons').show();
  },
  hide: function(api, options){
    $(api.element).find('.buttons').hide();
  }
});
</script>

app/views/layouts/_social_for_inspiration.html.erb
<div class="container-social">
  <div class='row-social'>
  	<div id="facebook facebook<%= inspiration.id %>" data-url="http://inspiredly.com/books/<%= book.id %>/inspirations/<%= inspiration.id %>" data-text="<%= inspiration.quote %>" data-title="Like"></div>
  	<div id=" twitter twitter<%= inspiration.id %>" data-url="http://inspiredly.com/books/<%= book.id %>/inspirations/<%= inspiration.id %>" data-text="<%= inspiration.quote %>" data-title="Tweet"></div>
  	<div id="pinterest pinterest<%= inspiration.id %>" data-url="http://inspiredly.com/books/<%= book.id %>/inspirations/<%= inspiration.id %>" data-text="<%= inspiration.quote %>" data-title="+1"></div>
  </div>  	
</div>

<script>
$('#twitter<%= inspiration.id %>').sharrre({
  share: {
    twitter: true
  },
  template: '<a class="box2" href="#"><i class='icon-twitter'></i><div class="count" href="#">{total}</div></a>',
  enableHover: false,
  enableTracking: true,
  buttons: { twitter: {via: '_JulienH'}},
  click: function(api, options){
    api.simulateClick();
    api.openPopup('twitter');
  }
});
$('#facebook<%= inspiration.id %>').sharrre({
  share: {
    facebook: true
  },
  template: '<a class="box2" href="#"><i class='icon-facebook'></i><div class="count" href="#">{total}</div></a>',
  enableHover: false,
  enableTracking: true,
  click: function(api, options){
    api.simulateClick();
    api.openPopup('facebook');
  }
});
$('#pinterest<%= inspiration.id %>').sharrre({
  share: {
    pinterest: true
  },
  template: '<a class="box2" href="#"><i class='icon-pinterest'></i><div class="count" href="#">{total}</div></a>',
  enableHover: false,
  enableTracking: true,
  click: function(api, options){
    api.simulateClick();
    api.openPopup('pinterest');
  }
});
</script>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Inspire</title>
  <%= stylesheet_link_tag    "application", media: "all", "data-turbolinks-track" => true %>
  <!-- styles needed by jScrollPane -->
  <link type="text/css" href="/assets/stylesheets/jquery.jscrollpane.css" rel="stylesheet" media="all" />

  <!-- the mousewheel plugin - optional to provide mousewheel support -->
  <script type="text/javascript" src="/assets/javascripts/jquery.mousewheel.js"></script>

  <!-- the jScrollPane script -->
  <script type="text/javascript" src="/assets/javascripts/jquery.jscrollpane.js"></script>
  <%= render 'layouts/jScrollpane' %>
  <%= javascript_include_tag "application", "data-turbolinks-track" => true %>
  <%= csrf_meta_tags %>
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
</head>
<body>
<%= render 'layouts/header' unless @disable_nav %>

<% flash.each do |name, msg| %>
    <% if msg.is_a?(String) %>
      <div class="alert alert-<%= name == :notice ? "success" : "danger" %> alert-dismissable">
        <button type="button" class="close" data-dismiss="alert" aria-hidden="true">&times;</button>
        <%= content_tag :div, msg, :id => "flash_#{name}" %>
      </div>
    <% end %>
  <% end %>

<%= yield %>

<%= javascript_tag do %>
     $(function() {
       $("time.timeago").timeago();
     });
   <% end %>

</body>
</html>